### ISSUE TITLE
Splunk Input not saving

### ISSUE THREAD

**Issue by phfa** [Cisco-AMP/amp4e_splunk_events_input#11]
Hi,

Splunk Version:  7.1.2
Cisco AMP for Endpoints Events Input
Version:    1.1.3
Build:    6 

We have configured the API with a read/write user and the connectivity is working between Splunk and AMP.
When we want to configure an input, we are able to see the different event types and groups in the drop list. However, when we try to save the configuration, it is failing with the below error message:

One of AMP for Endpoints API endpoints could not be reached (status 404). Please contact your Cisco AMP for Endpoints Administrator to resolve this issue.

Can you assist us ?
Thank you,

**Comment by AtyCisco** [comment]
Thanks for letting us know!
We are investigating the issue and will get back to you.

**Comment by phfa** [comment]
Hey AtyCisco,

By any chance did you have time to look into the issue ?

THankyou 
PF

**Comment by samsonnguyen** [comment]
Hi @phfa , could you tell us the hostname paramater and provide additional logs from the splunk app?
They can be found under `$SPLUNK_HOME/var/log/splunk/amp4e_events_input.log`

**Comment by phfa** [comment]
Hello Samson,

Please find attached the required logs and below print screen.

**Comment by marianomromano** [comment]
I have been unable to save the inputs at all.  No error but it just hangs.  Any thoughts?

**Comment by TheWoodRanger** [comment]
Same issue. We see a 404 in splunkd_ui_access.log when saving the input with it trying to hit: 
`/en-us/splunkd/__raw/servicesNS/admin/amp4e_events_input/data/inputs/amp4e_events_input?output_mode=json&_=1623868761510`

No error returned, no information. It just hangs. Seems a LOT of people are having this problem.
