### ISSUE TITLE
Splunk 7.x Retrieving Inputs

### ISSUE THREAD

**Issue by austintking** [Cisco-AMP/amp4e_splunk_events_input#2]
Hello,

We are currently running Splunk 7.x. When installing the TA, we are unable to retrieve the inputs on the first screen of the app. When we open the app, the first tab "inputs" just says "retrieving inputs" and never does so successfully.

We tested this on Splunk 6.x and it appears to work. We believe that this is a Splunk 7.x related bug with the application.

Thank you.

**Comment by samsonnguyen** [comment]
Hello, 

Thank you for raising this issue, unfortunately we do not have the capacity to perform out-of-band development to support Splunk 7.x at this time as it's not a critical threat/risk. However, we have tentatively scheduled some development/QA resources to address this issue for February. 
In the mean time, we would be happy to accept pull requests.

A work around for this is to install our app on a splunk 6.x heavy forwarder.

**Comment by samsonnguyen** [comment]
We've since released v1.1.5 of our app. Please give that app a go and re-open if necessary
