### ISSUE TITLE
Splunk Cloud Support

### ISSUE THREAD

**Issue by timhard-splunk** [Cisco-AMP/amp4e_splunk_events_input#24]
Has this app been submitted for Splunk Cloud support certification?

**Comment by rocketgoboom** [comment]
I submitted this app for Splunk Cloud approval and it did not meet security and functionality requirements for Splunk Cloud. Could the following changes be made to the app to get it approved for Splunk Cloud?

This is a preliminary report. More issues may be found upon further review. 
Thank you for your app install request. Your app did not meet security and functionality requirements for Splunk Cloud for the following reasons:
Blocking Concerns
•	check_for_secret_disclosure 
o	File: default/setup.xml Line: 16
The api_key is stored in inputs.conf in plain text. which is not permitted on Splunk Cloud. Please use storage/passwords endpoint to store the credentials.
o	File: bin/util/stream_consumer.py Line: 28
The self._url that includes password is written in log file in plain text, which is not permitted on Splunk Cloud. Please remove this line.
Once these issues are remedied you can resubmit your app for review

**Comment by pschulze** [comment]
Hi, [v1.1.8](https://github.com/Cisco-AMP/amp4e_splunk_events_input/releases/tag/v1.1.8) of the app addresses these problems and should meet the requirements for Splunk Cloud.
