### ISSUE TITLE
Hardcoded Splunk path

### ISSUE THREAD

**Issue by krispimk** [Cisco-AMP/amp4e_splunk_events_input#26]
**bin/util/api_service.py** and **./bin/splunklib/modularinput/validation_definition.py** and **default/inputs.conf** all have _/opt/splunk_ hard coded.  Some of us do not install on that path.  For example, we have installed our Splunk instance on _/opt/app/splunk_.  Can you please take out the hardcoded paths? 

Before finding that out I was receiving the following error:

 "Warning! We couldn’t retrieve the information from API with provided credentials. Please make sure the API host is accessible or re-configure the input with correct credentials."

**Comment by pschulze** [comment]
Hi mokarimi, `bin/util/api_service.py` and `default/inputs.conf` should have their absolute paths removed with #25 and version 1.1.7. I think the path you're referring to for splunk lib comes from [here](https://github.com/splunk/splunk-sdk-python/blob/master/splunklib/modularinput/validation_definition.py#L53) and that appears to just be documentation and should not affect the functionality of the app.
