### ISSUE TITLE
Computers list 

### ISSUE THREAD

**Issue by arock1972** [Cisco-AMP/amp4e_splunk_events_input#27]
Hi,
i am using this TA on our Splunk environment. it is great TA; working to collect event_streams and able to visualize activity.

https://api-docs.amp.cisco.com/api_actions/details?api_action=GET+%2Fv1%2Fcomputers&api_host=api.amp.cisco.com&api_resource=Computer&api_version=v1

question:
I also want to fetch computers list on a daily basis and index them - this is required for 'AV rollout status; clients with latest version etc.'  Do you have any other TA for such requirement? (or) is there a plan to enhance this TA?

I tried with custom python; pagination handling etc. but not working properly - it timed out and giving errors

https://github.com/CiscoSecurity/amp-02-fetch-computer-information

**Comment by samsonnguyen** [comment]
hi @arock1972, the computers endpoint on AMP for Endpoints is just a normal rest api. There are already many TA's for Splunk that can consume from rest apis.
I'm closing this issue as it's not really an issue pertaining to this app
