### ISSUE TITLE
Add Computer Inventory events

### ISSUE THREAD

**Issue by Memalor** [Cisco-AMP/amp4e_splunk_events_input#32]
Hello,
In addition to the cisco:amp:events,  is there a way to also pull the computers?

**Comment by Memalor** [comment]
There is a script called get_computers_list.py for this, but I want to integrate it into the forwarder.

**Comment by pschulze** [comment]
Hi Memalor, there's no way to get computers information from this app and we don't currently have any plans to add that in the future.

We do provide a [number of computers API endpoints](https://api-docs.amp.cisco.com/api_resources/Computer?api_host=api.amp.cisco.com&api_version=v1) that you can use to get data regarding your computers.

I'm not sure what that script is though, where is it from?

**Comment by Memalor** [comment]
https://github.com/CiscoSecurity/amp-01-basics/blob/master/02a_get_computers_list.py

**Comment by samsonnguyen** [comment]
We don't have plans to implement this as a new feature. 
Splunk already has many alternatives to importing json data from a generic rest API already.

Such as : https://splunkbase.splunk.com/app/1546/

The purpose of this app was to simplify only the amqp portion of the AMP for Endpoints event_streams for customers who who use AMP for Endpoints and Splunk as there was no good alternatives already on Splunkbase.
