### ISSUE TITLE
App not working with Splunk 8.0.1

### ISSUE THREAD

**Issue by ManBearRexsaurus** [Cisco-AMP/amp4e_splunk_events_input#33]
Hi

I have downloaded the development branch and tried to use the "docker-compose exec splunk sh -c "cd release;sudo fab splunkbase_release" command to build a package however I get an error "sudo: fab: command not found".
Seems like the app works when using docker image, but not sure how to build a standalone package to use in my environment.

**Comment by tmahn** [comment]
Hello ManBearRexsaurus,  we are currently working on this, but have no time estimate on when it will be done.  Support for python3 is being added and we are currently fixing some issues.

**Comment by ManBearRexsaurus** [comment]
Okay thank you.
