### ISSUE TITLE
Anyone have any luck getting this to work behind proxy?

### ISSUE THREAD

**Issue by greghelbig** [Cisco-AMP/amp4e_splunk_events_input#36]
We have installed this TA on 7.3.3 Splunk  on an instances that's behind a https proxy. We've configured splunk and the OS for the proxy and it the  api/initial setup seems to be working we see groups and event types but on connecting  to the stream export it fails and we collect no event data. Should this work or is it non supported/functional behind a proxy, I've read conflicting perspectives. Thank you!

2020-03-09 15:00:14,570 WARNING Amp4eEvents - Connection error (1583780414.57, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.17.102.100:443 failed: [Errno 111] Connection refused',))! Reconnecting in about 3 seconds

**Comment by samsonnguyen** [comment]
So i've actually taken a look and we are seeing that there is no way to get pika (python library) to play nice with proxies unless it's a totally transparent proxy at OCI layer 3/4

The protocol used to connect to AMP for stream consumption is done over amqp and not http. and it seems that most customers experiencing this issue are trying to use an https/http proxy for connection.

**Comment by samsonnguyen** [comment]
closing issue as wontfix.
For customers needing to use a proxy. 
Our suggestion is that the app should be placed on a heavy forward that is using a transparent proxy. As far as we can tell, amqp does not work with layer7 proxies (almost all of the http proxies like mitm)
