### ISSUE TITLE
Support for distributed/clustered environments

### ISSUE THREAD

**Issue by stevenbukovic** [Cisco-AMP/amp4e_splunk_events_input#4]
Requesting support for distributed/clustered environments.

Currently having an issue deploying this to a HF and forwarding events to clustered indexes.

Cannot update the index from main to forward to a clustered index.

**Comment by samsonnguyen** [comment]
We've tested the app on a clustered environment with custom clustered indexes.

**Steps to allow events to be forwarded to a custom clustered index:**
The heavy forwarder must first be aware of the clustered index before the index is presented in the drop-down list when configuring a new event stream input. This can be done by

* Log into the heavy forwarder's admin console
* Add a new index with the same name as the clustered index.
* Restarting the heavy forwarder
* Install the app and configure a new input, the custom index should be available as a selection for index.
* Once the app receives events, it should automatically forward the event to the clustered index.

NOTE: The app should be deployed to a _single_ heavy forwarder that forwards events to this clustered index. Having multiple apps (on multiple heavy forwarders) may cause a problem.

Closing as this seems to be working
