### ISSUE TITLE
Upgrading to Splunk 8.x has removed Input, and new Input is greyed out.

### ISSUE THREAD

**Issue by spodda01** [Cisco-AMP/amp4e_splunk_events_input#41]
After upgrading to Splunk Enterprise 8.x, cisco amp input got removed and new Input option is also greyed out.
Tried fresh installation of Cisco AMP for EndPoint (version 1.1.7) input but its still the same issue.

Can someone please confirm if the latest version of CiscoAMP is compatible with Splunk 8.x.

Thanks

**Comment by spodda01** [comment]
Hi, anyone can please help me with this issue ?

**Comment by samsonnguyen** [comment]
Our current version is not compatible with Splunk 8 yet. We suggest sticking with Splunk 7.x for the time being
