### ISSUE TITLE
Any plans to upgrade this add-on for Splunk 8 and Python 3?

### ISSUE THREAD

**Issue by rocketgoboom** [Cisco-AMP/amp4e_splunk_events_input#45]
This add-on is very useful to use for AMP data ingest into our Splunk Cloud environment. Would it be possible to upgrade to add-on to be supported by Splunk 8 / Python 3 / Splunk Cloud?

**Comment by samsonnguyen** [comment]
Hello,

We don't currently have immediate commitments to upgrading to python3 for Splunk8 support. This app is open-source and we accept community pull requests if anyone wants to take a stab at it.

It is a backlogged item, but we have no ETA on when we can get around to it

**Comment by samsonnguyen** [comment]
https://splunkbase.splunk.com/app/3670/#/details

We have just released v2 of the app which has been tested to work with Splunk v8.1.2
