### ISSUE TITLE
Splunk Cloud , unable to save configuration Cisco Amp App

### ISSUE THREAD

**Issue by bruggemanm** [Cisco-AMP/amp4e_splunk_events_input#48]

**Comment by bruggemanm** [comment]
Hi Guys,

We're facing some issues with one of our customers, they are using Splunk Cloud version 7.x and the Cisco AMP app version is 1.1.8 (which is compatible). The Splunk cloud team have installed the Cisco AMP app, but when we want to save the configuration it says "Configuration could not be saved" . Any guidance for this issue, besides to manually add config file through the Splunk Cloud team, that will not be easy.

**Comment by samsonnguyen** [comment]
https://splunkbase.splunk.com/app/3670/edit/#/hosting/19833

Please try again with v2.0.2 of the application
