### ISSUE TITLE
providing a way to access Operating System details

### ISSUE THREAD

**Issue by utiso** [Cisco-AMP/amp4e_splunk_events_input#50]
there doesn't appear to be a way to view operating system details (for vulns, etc).  
it looks like MAC addresses are pulled into all events.  
could you please consider doing the same for OS?

thanks!

**Comment by samsonnguyen** [comment]
This is a limitation of the Cisco Secure Endpoints (formerly AMP)'s event payloads.

This would have to be a feature request made to Cisco, and can be requested through Cisco TAC or your support contact for Secure endpoints. 

Closing this issue
