### ISSUE TITLE
Using the App for multiple customers/endpoints

### ISSUE THREAD

**Issue by cornerofcapp** [Cisco-AMP/amp4e_splunk_events_input#51]
Can I use the App to connect to multiple customer endpoints with different API Id/Keys? It cannot be done through the GUI, was wondering if modifying the inputs.conf via CLI would work ? Assume not.
Can I run multiple copies of the App (renaming it for different customers) on the same Splunk HF ?

**Comment by samsonnguyen** [comment]
We don't have plans to implement such a feature as it typically falls outside of our primary customer use-case and we have very limited resources available.

However, we are open to pull requests if someone would like a stab at making this happen
