### ISSUE TITLE
CISCO AMP does not work for Splunk Cloud 8.x

### ISSUE THREAD

**Issue by akamit225** [Cisco-AMP/amp4e_splunk_events_input#54]
Hello,
When we can get the updated version of CISCO AMP supporting the Splunk Cloud version 8.X

**Comment by akamit225** [comment]
Hey Guys, Could you please help us ,, any update

**Comment by ghost** [comment]
did someone manage to get this to work for Splunk V8?

**Comment by samsonnguyen** [comment]
https://splunkbase.splunk.com/app/3670/#/details

We have just released v2 of the app which has been tested to work with Splunk v8.1.2
