### ISSUE TITLE
Input Creation GUI does not list proper indexes on HF deployment

### ISSUE THREAD

**Issue by cdw-brendenmorgenthaler** [Cisco-AMP/amp4e_splunk_events_input#71]
With a HF connected to an indexer cluster the Input creation GUI only lists the indexes on the HF and does not query the cluster (though the REST api for example) to get the list of available indexes.

**Comment by samsonnguyen** [comment]
We've seen this happen when the HF does not have access to list the cluster's available indexes.
In some cases, there were licensing issues.

I would look into the heavy forwarder's configurations and ensure that it can correctly contact the indexers and has the correct credentials to query for available indexes
